main: io.github.techno_brony.tribula.sql.Main
name: TribulaSQL
version: 1.0
author: TechnoBrony
description: TribulaSQL
commands:
   sql:
      description: This is a demo command. #TODO
      usage: /<command>